#-----------------Tilt Matching Training Config-----------------
tm:
  a_end: 100.0
  buffer_chunk_size: 60
  buffer_print_samples: 0
  buffer_refresh_steps: 25
  control_variate: 1.0
  control_variate_ema: 0.04
  ema_decay: 0.95
  grad_accum_steps: 8
  h: 6.0
  learned_cv: false
  track_cv: false # when false, skip CV estimation/logging unless learned_cv is true
  loss_type: itm
  mix_batches: true
  num_batch_prompts: 12
  num_buffer_prompts: 40
  num_buffer_refresh: 10
  num_completions_per_prompt: 6
  rescale_logits: false
  rwd_shift: 0.0
  rwd_shift_auto: false
  steps_per_h: 1200 # this is the number of optimizer steps per h
  log_student: true
  log_temperature: 0.0
  student_log_steps: 300
  student_logs_per_prompt: 1
  use_ema: true
  use_sar_active_block_norm: true
  use_sar_discounted_future_loss: false
  sar_future_discount_alpha: 1.0

#-----------------Optimizer Config-----------------
adam_beta1: 0.9
adam_beta2: 0.99
adam_epsilon: 1e-8
weight_decay: 0.1

max_grad_norm: 2.0
learning_rate: 4e-6
lr_decay_ratio: 0.1
lr_min: 2e-6
lr_scheduler_type: linear
lr_warmup_ratio: 0.05

#-----------------Diffusion Generation Config-----------------
block_length: 32
cfg_scale: 0.0
diffusion_steps: 128
max_completion_length: 256
max_prompt_length: 172
remasking_strategy: "low_confidence"
sampling_temperature: 1.0

#-----------------Model Config-----------------
use_peft: true
torch_dtype: bfloat16
load_in_4bit: true
base_model_path: /n/netscratch/albergo_lab/Everyone/frank/hf_models/LLaDA-8B-Instruct

lora_r: 128
lora_alpha: 64
lora_dropout: 0.05
peft_task_type: CAUSAL_LM

#-----------------Logging and Checkpointing Config-----------------
checkpoint_dir: /n/netscratch/albergo_lab/Everyone/frank/llada_tm/ctd_ablate_h6.0
ckpt_freq: 100 # in optimizer steps
metrics_log_every: 1
resume_path: 
# leave empty if not resuming
student_copy_over: false

wandb:
  entity: "yuyuanchen-harvard-university"
  project: "LLaDA_TM"
  name: "ctd_ablate_h6"

#-----------------Other Training Config-----------------
dataset: countdown
max_rwd: 1.0
few_shot: 0
seed: 42
nodes: 1
devices: 1
world_size: 8
