#-----------------Tilt Matching Training Config-----------------
tm:
  a_end: 100.0
  buffer_chunk_size: 79
  buffer_print_samples: 0
  buffer_student_print_prob: 0.10
  control_variate: 1.0
  control_variate_ema: 0.04
  ema_decay: 0.996 # modified
  grad_accum_steps: 5
  h: 1.5
  learned_cv: false
  loss_type: itm
  num_batch_states: 20
  num_rebuilds_per_h: 1
  num_buffer_prompts: 79
  num_completions_per_prompt: 6
  ce_topk: 40
  loss_topk_in_block: 4
  rescale_logits: false
  rwd_shift: 0.0
  rwd_shift_auto: false
  steps_per_h: 600 # this is the number of optimizer steps per h
  log_student: true
  log_temperature: 0.0
  student_log_steps: 100
  student_logs_per_prompt: 1
  use_ema: true
  hat_wv_neg_thresh: -1e-8
  hat_wv_print_max: 10
  hat_wv_cum_print_every: 20
  hat_wv_cum_min_steps: 8
  hat_wv_cum_print_max: 30
  use_sar_active_block_norm: true

#-----------------Optimizer Config-----------------
adam_beta1: 0.9 # modified
adam_beta2: 0.996 # modified
adam_epsilon: 1e-8
weight_decay: 0.0 # modified

max_grad_norm: 1.0
learning_rate: 2e-5 # modified
lr_decay_ratio: 0.2
lr_min: 1e-5 # modified
lr_scheduler_type: linear
lr_warmup_ratio: 0.1

#-----------------Diffusion Generation Config-----------------
block_length: 32
cfg_scale: 0.0
diffusion_steps: 128
max_completion_length: 256
max_prompt_length: 240 # 240 for gsm
remasking_strategy: low_confidence
sampling_temperature: 1.0

#-----------------Model Config-----------------
use_peft: true
torch_dtype: bfloat16
load_in_4bit: true
base_model_path: /n/netscratch/albergo_lab/Everyone/frank/hf_models/LLaDA-8B-Instruct

lora_r: 128
lora_alpha: 64
lora_dropout: 0.05
peft_task_type: CAUSAL_LM

#-----------------Logging and Checkpointing Config-----------------
checkpoint_dir: /n/netscratch/albergo_lab/Everyone/frank/llada_tm/conf_aligned/gsm8k_top4/
ckpt_freq: 100 # in optimizer steps
metrics_log_every: 1
resume_path:
# leave empty if not resuming
student_copy_over: false

wandb:
  entity: "yuyuanchen-harvard-university"
  project: "LLaDA_TM"
  name: "gsm_conf_top4"

#-----------------Other Training Config-----------------
dataset: gsm8k
max_rwd: 1.0
few_shot: 0
seed: 42
nodes: 4
devices: 2
world_size: 8
