#-----------------Tilt Matching Training Config-----------------
tm:
  a_end: 100.0
  buffer_chunk_size: 4
  buffer_refresh_steps: 8
  buffer_print_samples: 4   # 0 disables printing
  control_variate: 1.5
  control_variate_ema: 0.1
  eval_num_prompts: 2
  eval_student_every: 2
  grad_accum_steps: 1
  h: 0.4
  learned_cv: false
  loss_type: itm
  num_batch_prompts: 2
  num_buffer_prompts: 4
  num_buffer_refresh: 2
  num_completions_per_prompt: 1
  rescale_logits: false
  rwd_shift: 0.0
  steps_per_h: 1800 # this is the number of optimizer steps per h

#-----------------Optimizer Config-----------------
adam_beta1: 0.9
adam_beta2: 0.99
adam_epsilon: 1e-8
weight_decay: 0.1

max_grad_norm: 1.5
learning_rate: 1e-5
lr_decay_ratio: 0.1
lr_min: 5e-6
lr_scheduler_type: linear
lr_warmup_ratio: 0.1

#-----------------Diffusion Generation Config-----------------
block_length: 32
cfg_scale: 0.0 #TODO: check
diffusion_steps: 128
max_completion_length: 256
max_prompt_length: 240
remasking_strategy: random # or random
sampling_temperature: 1.0

#-----------------Model Config-----------------
use_peft: true
torch_dtype: bfloat16
load_in_4bit: true
base_model_path: /n/netscratch/albergo_lab/Everyone/frank/hf_models/LLaDA-8B-Instruct
# don't implement any attention for llada

lora_r: 128
lora_alpha: 64
lora_dropout: 0.05
peft_task_type: CAUSAL_LM

#-----------------Logging and Checkpointing Config-----------------
checkpoint_dir: /n/netscratch/albergo_lab/Everyone/frank/llada_tm/gsm8k_long_ckpt_test
checkpoint_freq: 2  # in number of optimizer steps
metrics_log_every: 2
resume_path: #/n/netscratch/albergo_lab/Everyone/frank/llada_tm/gsm8k_new/checkpoint-a-3.000.ckpt
# leave empty if not resuming
wandb:
  entity: "yuyuanchen-harvard-university"
  project: "LLaDA_TM"
  name: "gsm_long_test"

#-----------------Other Training Config-----------------
dataset: "gsm8k"
max_rwd: 3.0
few_shot: 0
seed: 42
nodes: 1
devices: 1 # 8? 4?
debug_loss_spike_threshold: 60
debug_loss_spike_topk: 3
