#-----------------Tilt Matching Training Config-----------------
tm:
  a_end: 100.0
  buffer_chunk_size: 96
  buffer_refresh_steps: 32
  buffer_print_samples: 32   # 0 disables printing
  # buffer_print_max_chars: 600
  control_variate: 30
  control_variate_ema: 0.05
  grad_accum_steps: 1
  h: 5.0
  loss_type: itm
  num_batch_prompts: 1
  num_buffer_prompts: 8
  num_buffer_refresh: 1
  num_completions_per_prompt: 1
  rescale_logits: false
  rwd_shift: 0.0
  steps_per_h: 2 # this is the number of optimizer steps per h

#-----------------Optimizer Config-----------------
adam_beta1: 0.9
adam_beta2: 0.99
adam_epsilon: 1e-8
weight_decay: 0.1

max_grad_norm: 1.0
learning_rate: 3e-6
lr_decay_ratio: 0.1
lr_min: 1e-6
lr_scheduler_type: linear
lr_warmup_ratio: 0.15

#-----------------Diffusion Generation Config-----------------
block_length: 32
cfg_scale: 0.0 #TODO: check
diffusion_steps: 128
max_completion_length: 256
max_prompt_length: 240
remasking_strategy: low_confidence # or random
sampling_temperature: 1.0

#-----------------Model Config-----------------
use_peft: true
torch_dtype: bfloat16
load_in_4bit: true
base_model_path: /n/netscratch/albergo_lab/Everyone/frank/hf_models/LLaDA-8B-Instruct
# don't implement any attention for llada

lora_r: 128
lora_alpha: 64
lora_dropout: 0.05
peft_task_type: CAUSAL_LM

#-----------------Logging and Checkpointing Config-----------------
checkpoint_dir: /n/netscratch/albergo_lab/Everyone/frank/llada_tm/gsm8k_new
checkpoint_freq: 5.0  # in units of h
metrics_log_every: 4
resume_path: /n/netscratch/albergo_lab/Everyone/frank/llada_tm/gsm8k_new/checkpoint-a-3.000.ckpt
# leave empty if not resuming
# wandb:
#   entity: "yuyuanchen-harvard-university"
#   project: "LLaDA_TM"
#   name: "gsm_phase1"

#-----------------Other Training Config-----------------
dataset: "gsm8k"
max_rwd: 4.0
few_shot: 0
seed: 42
nodes: 1
devices: 1 # 8? 4?
debug_loss_spike_threshold: 60
debug_loss_spike_topk: 3
