#-----------------Tilt Matching Training Config-----------------
tm:
  a_end: 100.0
  buffer_chunk_size: 50
  buffer_refresh_steps: 12
  buffer_print_samples: 4   # 0 disables printing
  control_variate: 1.0
  control_variate_ema: 0.04
  eval_num_prompts: 40
  eval_student_every: 96
  grad_accum_steps: 3
  h: 2.5
  learned_cv: false
  loss_type: itm
  num_batch_prompts: 5
  num_buffer_prompts: 60
  num_buffer_refresh: 20
  num_completions_per_prompt: 5
  rescale_logits: false
  rwd_shift: -2.0
  steps_per_h: 380 # this is the number of optimizer steps per h

#-----------------Optimizer Config-----------------
adam_beta1: 0.9
adam_beta2: 0.99
adam_epsilon: 1e-8
weight_decay: 0.1

max_grad_norm: 3.0
learning_rate: 6e-6
lr_decay_ratio: 0.1
lr_min: 3e-6
lr_scheduler_type: linear
lr_warmup_ratio: 0

#-----------------Diffusion Generation Config-----------------
block_length: 32
cfg_scale: 0.0
diffusion_steps: 128
max_completion_length: 256
max_prompt_length: 240
remasking_strategy: random # or low_confidence
sampling_temperature: 1.0

#-----------------Model Config-----------------
use_peft: true
torch_dtype: bfloat16
load_in_4bit: true
base_model_path: /n/netscratch/albergo_lab/Everyone/frank/hf_models/LLaDA-8B-Instruct

lora_r: 128
lora_alpha: 64
lora_dropout: 0.05
peft_task_type: CAUSAL_LM

#-----------------Logging and Checkpointing Config-----------------
checkpoint_dir: /n/netscratch/albergo_lab/Everyone/frank/llada_tm/gsm8k_long_noconf
checkpoint_freq: 48  # in number of optimizer steps
metrics_log_every: 1
resume_path: # /n/netscratch/albergo_lab/Everyone/frank/llada_tm/gsm8k_small_h/checkpoint-a-0.900.ckpt
# leave empty if not resuming
wandb:
  entity: "yuyuanchen-harvard-university"
  project: "LLaDA_TM"
  name: "gsm_long"

#-----------------Other Training Config-----------------
dataset: "gsm8k"
few_shot: 0
seed: 42
nodes: 2
devices: 4  # 8? 4?
